server:
  port: 9090

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

spring:
  redis:
    host:
    password:
    database: 2   # 使用2号数据库
    port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/sp_security?characterEncoding=utf-8&serverTimezone=UTC
    username: HildaData
    password: 22222l22222123
    driver-class-name: com.mysql.cj.jdbc.Driver